package jirawatch

import (
	"fmt"
	"strings"

	"github.com/jahwag/clem/internal/config"
)

const (
	defaultPollSeconds     = 60
	defaultDebounceSeconds = 5
)

const watchScriptTemplate = `#!/bin/bash
# clem-jira-watch-{{.Project}}-{{.AgentKey}}.sh — generated by clem provision
# Polls Jira for new claimable tasks and wakes the agent tmux session.

SITE="{{.JiraSite}}"
PROJECT="{{.JiraProject}}"
LABEL="{{.TaskLabel}}"
JQL_EXTRA="{{.JQLExtra}}"
AGENT_KEY="{{.AgentKey}}"
POLL_INTERVAL={{.PollSeconds}}
DEBOUNCE={{.DebounceSeconds}}
BACKOFF=0
MAX_BACKOFF=900
STATE_FILE="$HOME/.claude/jira-watch.state"
LOGFILE="$HOME/.claude/{{.AgentKey}}-jira-watch.log"

mkdir -p "$HOME/.claude"
[ -f "$HOME/.env" ] && source "$HOME/.env"
{{.ProxyExport}}

log() { echo "$(date -Iseconds) $1" | tee -a "$LOGFILE"; }

load_state() {
    OLD_IDS=""
    HAD_STATE_FILE=0
    if [ -f "$STATE_FILE" ]; then
        HAD_STATE_FILE=1
        OLD_IDS=$(grep '^ids=' "$STATE_FILE" 2>/dev/null | cut -d= -f2- || true)
    fi
}

save_state() {
    local last_wake_line=""
    [ -f "$STATE_FILE" ] && last_wake_line=$(grep '^last_wake=' "$STATE_FILE" 2>/dev/null || true)
    {
        printf 'ids=%s\n' "$NEW_IDS"
        [ -n "$last_wake_line" ] && echo "$last_wake_line"
    } > "$STATE_FILE"
}

maybe_wake() {
    local now last
    now=$(date +%s)
    last=0
    [ -f "$STATE_FILE" ] && last=$(grep '^last_wake=' "$STATE_FILE" 2>/dev/null | cut -d= -f2 || echo 0)
    if (( now - last < DEBOUNCE )); then
        return
    fi
    if tmux has-session -t "$AGENT_KEY" 2>/dev/null; then
        tmux send-keys -t "$AGENT_KEY" "" Enter
        log "woke tmux session $AGENT_KEY (new claimable Jira issues)"
    fi
    if grep -q '^last_wake=' "$STATE_FILE" 2>/dev/null; then
        sed -i "s/^last_wake=.*/last_wake=$now/" "$STATE_FILE"
    else
        echo "last_wake=$now" >> "$STATE_FILE"
    fi
}

poll_once() {
    if [ -z "$JIRA_API_TOKEN" ] || [ -z "$JIRA_USERNAME" ]; then
        log "JIRA_API_TOKEN or JIRA_USERNAME unset — skipping poll"
        return
    fi
    load_state
    local jql="project = ${PROJECT} AND labels = \"${LABEL}\" AND assignee is EMPTY"
    [ -n "$JQL_EXTRA" ] && jql="${jql} ${JQL_EXTRA}"
    local all_keys="" page_token="" body code payload page_result page_keys
    while true; do
        body=$(mktemp)
        payload=$(python3 -c "import json,sys; jql=sys.argv[1]; token=sys.argv[2]; req={'jql':jql,'fields':['key'],'maxResults':50}; token and req.update({'nextPageToken':token}); print(json.dumps(req))" "$jql" "$page_token")
        code=$(curl -sS -o "$body" -w '%{http_code}' \
            -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            -d "$payload" \
            "https://${SITE}/rest/api/3/search/jql")
        if [ "$code" = "429" ] || [ "$code" = "401" ]; then
            log "Jira API returned HTTP $code — backing off"
            if [ "$BACKOFF" -eq 0 ]; then
                BACKOFF=60
            else
                BACKOFF=$(( BACKOFF * 2 ))
                [ "$BACKOFF" -gt "$MAX_BACKOFF" ] && BACKOFF="$MAX_BACKOFF"
            fi
            rm -f "$body"
            return
        fi
        if [ "$code" != "200" ]; then
            log "Jira API returned HTTP $code"
            BACKOFF=0
            rm -f "$body"
            return
        fi
        BACKOFF=0
        page_result=$(python3 -c "
import json,sys
try:
    data=json.load(open(sys.argv[1]))
except Exception:
    print()
    print('---')
    print()
    sys.exit(0)
keys=[i.get('key','') for i in (data.get('issues') or []) if isinstance(i,dict) and i.get('key')]
token=data.get('nextPageToken') or ''
print(' '.join(keys))
print('---')
print(token)
" "$body")
        page_keys=$(echo "$page_result" | sed -n '1p')
        page_token=$(echo "$page_result" | sed -n '3p')
        if [ -n "$page_keys" ]; then
            all_keys="${all_keys} ${page_keys}"
        fi
        rm -f "$body"
        [ -z "$page_token" ] && break
    done
    NEW_IDS=$(echo "$all_keys" | tr ' ' '\n' | sed '/^$/d' | LC_ALL=C sort -u | tr '\n' ' ' | sed 's/ $//')
    if [ "$HAD_STATE_FILE" -eq 1 ]; then
        if comm -13 <(echo "$OLD_IDS" | tr ' ' '\n' | LC_ALL=C sort) <(echo "$NEW_IDS" | tr ' ' '\n' | LC_ALL=C sort) | grep -q .; then
            maybe_wake
        fi
    fi
    save_state
}

log "starting Jira issue watcher for $SITE project=$PROJECT label=$LABEL poll=${POLL_INTERVAL}s"
while true; do
    poll_once
    if [ "$BACKOFF" -gt 0 ]; then
        log "sleeping ${BACKOFF}s after rate limit"
        sleep "$BACKOFF"
    else
        sleep "$POLL_INTERVAL"
    fi
done
`

const serviceTemplate = `[Unit]
Description=Clem Jira issue watcher: {{.AgentName}} ({{.Project}})
After=clem-{{.Project}}-{{.AgentKey}}.service
{{.ProxyUnitDeps}}BindsTo=clem-{{.Project}}-{{.AgentKey}}.service
PartOf=clem-{{.Project}}-{{.AgentKey}}.service
JoinsNamespaceOf=clem-{{.Project}}-{{.AgentKey}}.service

[Service]
Type=simple
User={{.OSUser}}
PrivateTmp=yes
ExecStart={{.HomeDir}}/.local/bin/clem-jira-watch.sh
Restart=on-failure
RestartSec=10
{{.EgressDirectives}}
[Install]
WantedBy=multi-user.target
`

type params struct {
	Project          string
	AgentKey         string
	AgentName        string
	OSUser           string
	HomeDir          string
	JiraSite         string
	JiraProject      string
	TaskLabel        string
	JQLExtra         string
	PollSeconds      int
	DebounceSeconds  int
	ProxyExport      string
	ProxyUnitDeps    string
	EgressDirectives string
}

// GenerateScript renders the per-agent Jira issue watcher script.
func GenerateScript(cfg *config.Config, agentKey string) string {
	ac := cfg.Agents[agentKey]
	taskLabel := cfg.Coordination.Channels["tasks"]
	if taskLabel == "" {
		taskLabel = "clem-todo"
	}
	p := params{
		Project:          cfg.Project,
		AgentKey:         agentKey,
		AgentName:        ac.Name,
		OSUser:           cfg.OSUsername(agentKey),
		HomeDir:          fmt.Sprintf("/home/%s", cfg.OSUsername(agentKey)),
		JiraSite:         cfg.Coordination.Jira.Site,
		JiraProject:      cfg.Coordination.Jira.Project,
		TaskLabel:        taskLabel,
		JQLExtra:         cfg.Coordination.Jira.JQLExtra,
		PollSeconds:      defaultPollSeconds,
		DebounceSeconds:  defaultDebounceSeconds,
		ProxyExport:      proxyExportBlock(cfg, agentKey),
		EgressDirectives: egressDirectives(cfg, agentKey),
	}
	return render(watchScriptTemplate, p)
}

// GenerateService renders the systemd unit for the Jira issue watcher sidecar.
func GenerateService(cfg *config.Config, agentKey string) string {
	ac := cfg.Agents[agentKey]
	p := params{
		Project:          cfg.Project,
		AgentKey:         agentKey,
		AgentName:        ac.Name,
		OSUser:           cfg.OSUsername(agentKey),
		HomeDir:          fmt.Sprintf("/home/%s", cfg.OSUsername(agentKey)),
		ProxyUnitDeps:    proxyUnitDeps(cfg, agentKey),
		EgressDirectives: egressDirectives(cfg, agentKey),
	}
	return render(serviceTemplate, p)
}

func proxyExportBlock(cfg *config.Config, agentKey string) string {
	if !cfg.EgressEnabledFor(agentKey) {
		return ""
	}
	port := cfg.Egress.ProxyPortOrDefault()
	return fmt.Sprintf(`export HTTPS_PROXY=http://127.0.0.1:%d
export HTTP_PROXY=http://127.0.0.1:%d
export NO_PROXY=127.0.0.1,localhost,::1`, port, port)
}

const egressDirectivesBlock = `# Same loopback-only egress guard as the agent service.
IPAddressDeny=any
IPAddressAllow=127.0.0.0/8
IPAddressAllow=::1/128
`

func egressDirectives(cfg *config.Config, agentKey string) string {
	if cfg.EgressEnabledFor(agentKey) {
		return egressDirectivesBlock
	}
	return ""
}

func proxyUnitDeps(cfg *config.Config, agentKey string) string {
	if !cfg.EgressEnabledFor(agentKey) {
		return ""
	}
	return fmt.Sprintf("After=%s\nWants=%s\n",
		cfg.PipelockServiceName(), cfg.PipelockServiceName())
}

func render(tmpl string, p params) string {
	r := strings.NewReplacer(
		"{{.Project}}", p.Project,
		"{{.AgentKey}}", p.AgentKey,
		"{{.AgentName}}", p.AgentName,
		"{{.OSUser}}", p.OSUser,
		"{{.HomeDir}}", p.HomeDir,
		"{{.JiraSite}}", p.JiraSite,
		"{{.JiraProject}}", p.JiraProject,
		"{{.TaskLabel}}", p.TaskLabel,
		"{{.JQLExtra}}", p.JQLExtra,
		"{{.PollSeconds}}", fmt.Sprintf("%d", p.PollSeconds),
		"{{.DebounceSeconds}}", fmt.Sprintf("%d", p.DebounceSeconds),
		"{{.ProxyExport}}", p.ProxyExport,
		"{{.ProxyUnitDeps}}", p.ProxyUnitDeps,
		"{{.EgressDirectives}}", p.EgressDirectives,
	)
	return r.Replace(tmpl)
}
