package jirawatch

import (
	"fmt"
	"strings"

	"github.com/jahwag/clem/internal/config"
)

const (
	defaultPollSeconds     = 60
	defaultDebounceSeconds = 5
)

const watchScriptTemplate = `#!/bin/bash
# clem-jira-watch-{{.Project}}-{{.AgentKey}}.sh — generated by clem provision
# Polls Jira for new claimable tasks and wakes the agent tmux session.

SITE="{{.JiraSite}}"
PROJECT="{{.JiraProject}}"
LABEL="{{.TaskLabel}}"
JQL_EXTRA="{{.JQLExtra}}"
AGENT_KEY="{{.AgentKey}}"
POLL_INTERVAL={{.PollSeconds}}
DEBOUNCE={{.DebounceSeconds}}
STATE_FILE="$HOME/.claude/jira-watch.state"
LOGFILE="$HOME/.claude/{{.AgentKey}}-jira-watch.log"

mkdir -p "$HOME/.claude"
[ -f "$HOME/.env" ] && source "$HOME/.env"
{{.ProxyExport}}

log() { echo "$(date -Iseconds) $1" | tee -a "$LOGFILE"; }

load_state() {
    OLD_IDS=""
    HAD_STATE_FILE=0
    if [ -f "$STATE_FILE" ]; then
        HAD_STATE_FILE=1
        OLD_IDS=$(grep '^ids=' "$STATE_FILE" 2>/dev/null | cut -d= -f2- || true)
    fi
}

save_state() {
    local last_wake_line=""
    [ -f "$STATE_FILE" ] && last_wake_line=$(grep '^last_wake=' "$STATE_FILE" 2>/dev/null || true)
    {
        printf 'ids=%s\n' "$NEW_IDS"
        [ -n "$last_wake_line" ] && echo "$last_wake_line"
    } > "$STATE_FILE"
}

maybe_wake() {
    local now last
    now=$(date +%s)
    last=0
    [ -f "$STATE_FILE" ] && last=$(grep '^last_wake=' "$STATE_FILE" 2>/dev/null | cut -d= -f2 || echo 0)
    if (( now - last < DEBOUNCE )); then
        return
    fi
    if tmux has-session -t "$AGENT_KEY" 2>/dev/null; then
        tmux send-keys -t "$AGENT_KEY" "" Enter
        log "woke tmux session $AGENT_KEY (new claimable Jira issues)"
    fi
    if grep -q '^last_wake=' "$STATE_FILE" 2>/dev/null; then
        sed -i "s/^last_wake=.*/last_wake=$now/" "$STATE_FILE"
    else
        echo "last_wake=$now" >> "$STATE_FILE"
    fi
}

poll_once() {
    if [ -z "$JIRA_API_TOKEN" ] || [ -z "$JIRA_USERNAME" ]; then
        log "JIRA_API_TOKEN or JIRA_USERNAME unset — skipping poll"
        return
    fi
    load_state
    local body code
    body=$(mktemp)
    trap 'rm -f "$body"' RETURN
    local jql="project = ${PROJECT} AND labels = \"${LABEL}\" AND assignee is EMPTY"
    [ -n "$JQL_EXTRA" ] && jql="${jql} ${JQL_EXTRA}"
    code=$(curl -sS -o "$body" -w '%{http_code}' \
        -u "$JIRA_USERNAME:$JIRA_API_TOKEN" \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        -d "{\"jql\":\"${jql}\",\"fields\":[\"key\"],\"maxResults\":30}" \
        "https://${SITE}/rest/api/3/search")
    if [ "$code" != "200" ]; then
        log "Jira API returned HTTP $code"
        return
    fi
    NEW_IDS=$(python3 -c "
import json,sys
try:
    data=json.load(open(sys.argv[1]))
except Exception:
    sys.exit(0)
issues=data.get('issues') or []
keys=sorted(i.get('key','') for i in issues if isinstance(i,dict) and i.get('key'))
print(' '.join(keys))
" "$body" 2>/dev/null || true)
    if [ "$HAD_STATE_FILE" -eq 1 ]; then
        if comm -13 <(echo "$OLD_IDS" | tr ' ' '\n' | LC_ALL=C sort) <(echo "$NEW_IDS" | tr ' ' '\n' | LC_ALL=C sort) | grep -q .; then
            maybe_wake
        fi
    fi
    save_state
}

log "starting Jira issue watcher for $SITE project=$PROJECT label=$LABEL poll=${POLL_INTERVAL}s"
while true; do
    poll_once
    sleep "$POLL_INTERVAL"
done
`

const serviceTemplate = `[Unit]
Description=Clem Jira issue watcher: {{.AgentName}} ({{.Project}})
After=clem-{{.Project}}-{{.AgentKey}}.service
{{.ProxyUnitDeps}}BindsTo=clem-{{.Project}}-{{.AgentKey}}.service
PartOf=clem-{{.Project}}-{{.AgentKey}}.service
JoinsNamespaceOf=clem-{{.Project}}-{{.AgentKey}}.service

[Service]
Type=simple
User={{.OSUser}}
PrivateTmp=yes
ExecStart={{.HomeDir}}/.local/bin/clem-jira-watch.sh
Restart=on-failure
RestartSec=10
{{.EgressDirectives}}
[Install]
WantedBy=multi-user.target
`

type params struct {
	Project          string
	AgentKey         string
	AgentName        string
	OSUser           string
	HomeDir          string
	JiraSite         string
	JiraProject      string
	TaskLabel        string
	JQLExtra         string
	PollSeconds      int
	DebounceSeconds  int
	ProxyExport      string
	ProxyUnitDeps    string
	EgressDirectives string
}

// GenerateScript renders the per-agent Jira issue watcher script.
func GenerateScript(cfg *config.Config, agentKey string) string {
	ac := cfg.Agents[agentKey]
	taskLabel := cfg.Coordination.Channels["tasks"]
	if taskLabel == "" {
		taskLabel = "clem-todo"
	}
	p := params{
		Project:          cfg.Project,
		AgentKey:         agentKey,
		AgentName:        ac.Name,
		OSUser:           cfg.OSUsername(agentKey),
		HomeDir:          fmt.Sprintf("/home/%s", cfg.OSUsername(agentKey)),
		JiraSite:         cfg.Coordination.Jira.Site,
		JiraProject:      cfg.Coordination.Jira.Project,
		TaskLabel:        taskLabel,
		JQLExtra:         cfg.Coordination.Jira.JQLExtra,
		PollSeconds:      defaultPollSeconds,
		DebounceSeconds:  defaultDebounceSeconds,
		ProxyExport:      proxyExportBlock(cfg, agentKey),
		EgressDirectives: egressDirectives(cfg, agentKey),
	}
	return render(watchScriptTemplate, p)
}

// GenerateService renders the systemd unit for the Jira issue watcher sidecar.
func GenerateService(cfg *config.Config, agentKey string) string {
	ac := cfg.Agents[agentKey]
	p := params{
		Project:          cfg.Project,
		AgentKey:         agentKey,
		AgentName:        ac.Name,
		OSUser:           cfg.OSUsername(agentKey),
		HomeDir:          fmt.Sprintf("/home/%s", cfg.OSUsername(agentKey)),
		ProxyUnitDeps:    proxyUnitDeps(cfg, agentKey),
		EgressDirectives: egressDirectives(cfg, agentKey),
	}
	return render(serviceTemplate, p)
}

func proxyExportBlock(cfg *config.Config, agentKey string) string {
	if !cfg.EgressEnabledFor(agentKey) {
		return ""
	}
	port := cfg.Egress.ProxyPortOrDefault()
	return fmt.Sprintf(`export HTTPS_PROXY=http://127.0.0.1:%d
export HTTP_PROXY=http://127.0.0.1:%d
export NO_PROXY=127.0.0.1,localhost,::1`, port, port)
}

const egressDirectivesBlock = `# Same loopback-only egress guard as the agent service.
IPAddressDeny=any
IPAddressAllow=127.0.0.0/8
IPAddressAllow=::1/128
`

func egressDirectives(cfg *config.Config, agentKey string) string {
	if cfg.EgressEnabledFor(agentKey) {
		return egressDirectivesBlock
	}
	return ""
}

func proxyUnitDeps(cfg *config.Config, agentKey string) string {
	if !cfg.EgressEnabledFor(agentKey) {
		return ""
	}
	return fmt.Sprintf("After=%s\nWants=%s\n",
		cfg.PipelockServiceName(), cfg.PipelockServiceName())
}

func render(tmpl string, p params) string {
	r := strings.NewReplacer(
		"{{.Project}}", p.Project,
		"{{.AgentKey}}", p.AgentKey,
		"{{.AgentName}}", p.AgentName,
		"{{.OSUser}}", p.OSUser,
		"{{.HomeDir}}", p.HomeDir,
		"{{.JiraSite}}", p.JiraSite,
		"{{.JiraProject}}", p.JiraProject,
		"{{.TaskLabel}}", p.TaskLabel,
		"{{.JQLExtra}}", p.JQLExtra,
		"{{.PollSeconds}}", fmt.Sprintf("%d", p.PollSeconds),
		"{{.DebounceSeconds}}", fmt.Sprintf("%d", p.DebounceSeconds),
		"{{.ProxyExport}}", p.ProxyExport,
		"{{.ProxyUnitDeps}}", p.ProxyUnitDeps,
		"{{.EgressDirectives}}", p.EgressDirectives,
	)
	return r.Replace(tmpl)
}
